name: liampage.com
favicon: null
layout_spectrum: 0
typography_spectrum: 0.7593
title: liampage.com
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d5d4a8'
    - '#091e2f'
    - '#3a433e'
    - '#95896f'
    - '#7b6c57'
  brandStrength: 0.375
  lightness: 0.125
  saturation: 1
  rhythmicContrast: 1
purpose: []
