name: liampage.com
favicon: null
layout_spectrum: 0.9705749535933137
typography_spectrum: 0.16019113990478218
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.36342793656513095
  lightness: 0.7923649286385626
  saturation: 0.8663439876399934
  rhythmicContrast: 0.7239711254369467
purpose: []
